name: Run on AArch64
on: [push, pull_request]

jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: uraimo/run-on-arch-action@v2.0.7
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          env: |
            test_env: abc
            another_env: xyz
          install: |
            apt-get update
            apt-get install -y curl git g++ python python3 cmake
          run: |
            uname -a
            python3 --version
            echo ${test_env}
            echo ${another_env}
            git clone https://github.com/ryuichis/oclint
            cd oclint
            git checkout use-system-llvm
            cd oclint-scripts
            ./clang
            ./googleTest co
            ./googleTest build
            ./test core -no-ninja
          
